{{- $fullName := include "fullName" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  namespace: {{ include "namespace" . }}
  labels:
    app: {{ $fullName }}
    helmVersion: {{ .Chart.Version }}
    helmAppVersion: {{ .Chart.AppVersion }}
    helmName: {{ .Chart.Name }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.scale.replicaCount }}
{{- end }}
  serviceName: {{ $fullName }}
  podManagementPolicy: "Parallel"
  template:
    metadata:
      name: {{ $fullName }}
      labels:
        app: {{ $fullName }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - {{ .Values.node.targetOS }}
              - key: kubernetes.io/arch
                operator: In
                values:
                - {{ .Values.node.targetArch }}
              - key: kubernetes.azure.com/os-sku
                operator: In
                values:
                - {{ .Values.node.targetSku }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - {{ $fullName }}
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      containers:
      - name: recording-bot
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        lifecycle:
          preStop:
            exec:
              command:
              - powershell
              - Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine;
              - .\halt_termination.ps1
        ports:
        - containerPort: {{ .Values.internal.port }}
        - containerPort: {{ .Values.internal.media }}
        volumeMounts:
        - mountPath: "C:/certs/"
          name: certificate
          readOnly: true
        env:
        - name: AzureSettings__BotName
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.resourceName }}
              key: botName
        - name: AzureSettings__AadAppId
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.resourceName }}
              key: applicationId
        - name: AzureSettings__AadAppSecret
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.resourceName }}
              key: applicationSecret
        - name: AzureSettings__ServicePath
          value: {{ include "ingress.path.withTrailingSlash" . }}
        - name: AzureSettings__ServiceDnsName
          value: {{ include "hostName" . }}
        - name: AzureSettings__InstancePublicPort
          value: "{{ .Values.public.media }}"
        - name: AzureSettings__InstanceInternalPort
          value: "{{ .Values.internal.media }}"
        - name: AzureSettings__CallSignalingPort
          value: "{{ .Values.internal.port }}"
        - name: AzureSettings__CallSignalingPublicPort
          value: "{{ .Values.public.https }}"
        - name: AzureSettings__PlaceCallEndpointUrl
          value: https://graph.microsoft.com/v1.0
        - name: AzureSettings__CaptureEvents
          value: "{{ .Values.container.env.azureSetting.captureEvents }}"
        - name: AzureSettings__EventsFolder
          value: "{{ .Values.container.env.azureSetting.eventsFolder }}"
        - name: AzureSettings__MediaFolder
          value: "{{ .Values.container.env.azureSetting.mediaFolder }}"
        - name: AzureSettings__TopicKey
          value: "{{ .Values.container.env.azureSetting.eventhubKey }}"
        - name: AzureSettings__TopicName
          value: "{{ .Values.container.env.azureSetting.eventhubName }}"
        - name: AzureSettings__RegionName
          value: "{{ .Values.container.env.azureSetting.eventhubRegion }}"
        - name: AzureSettings__IsStereo
          value: "{{ .Values.container.env.azureSetting.isStereo }}"
        - name: AzureSettings__WAVSampleRate
          value: "{{ .Values.container.env.azureSetting.wavSampleRate }}"
        - name: AzureSettings__WAVQuality
          value: "{{ .Values.container.env.azureSetting.wavQuality }}"
        - name: AzureSettings__PodName
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: certificate
        secret:
          secretName: {{ include "ingress.tls.secretName" . }}
      imagePullSecrets:
      - name: acr-secret
  selector:
    matchLabels:
      app: {{ $fullName }}
