name: .NET BOT D1 BUILD {OrgName}

on:
  push:
    branches:
      - '{BranchName}'
    paths:
      - './Samples/PublicSamples/EchoBot/src/**'
      - .github/workflows/echobot-build-{OrgName}.yml

  pull_request:
    branches:
      - '{BranchName}'
    paths:
      - './Samples/PublicSamples/EchoBot/src/**'
      - .github/workflows/echobot-build-{OrgName}.yml

  workflow_dispatch:

env:
  # /home/runner/work/publish
  Base:        publish
  Component:   EchoBot
  BuildName:   0.1.${{ github.run_number }}
  Environment: D1
  OrgName:     {OrgName}
  Location:    {Location}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Run pwsh
      shell: pwsh
      run: | 
        echo "${{ env.Base }}/${{ env.Component }}/${{ env.BuildName }}/"
    - uses: nuget/setup-nuget@v1
    - run: nuget restore Samples\PublicSamples\EchoBot\src\EchoBot.sln
    
    - name: Create Build Directory
      run: mkdir ${{ env.Base }}/${{ env.Component }}/${{ env.BuildName }}/
    
    - name: Build Solution
      run: |
        msbuild.exe Samples\PublicSamples\EchoBot\src\EchoBot.sln /nologo /p:platform="x64" /p:OutDir=${{ github.workspace }}/${{ env.Base }}/${{ env.Component }}/${{ env.BuildName }}/
        
    - name: Run pwsh
      shell: pwsh
      run: | 
        Get-ChildItem -Path ${{ github.workspace }}\${{ env.Base }}\${{ env.Component }}\${{ env.BuildName }}\
        echo ${{ github.workspace }}
    
    - name: Login via Az module
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_{OrgName}_BOT }}
        enable-AzPSSession: true

    - name: G1_RG_UploadArtifacts_to_Blob
      uses: Azure/powershell@v2
      with:
        inlineScript: |
          Get-ChildItem -Path  ./${{ env.Base }}/${{ env.Component }}/${{ env.BuildName }}/ # -Recurse

          $Params = @{
            App           = 'BOT'
            BuildName     = $env:BuildName
            ComponentName = $env:Component
            BasePath      = $env:Base
            OrgName       = $env:OrgName
            Location      = $env:location
          }
          & ./Samples/PublicSamples/EchoBot/ADF/release-az/Sync-AzBuildComponent.ps1 @Params
        azPSVersion: latest

    - name: G1_RG_UpdateBuildMeta_to_Blob
      uses: Azure/powershell@v2
      with:
        inlineScript: |
          echo $home
          ls $home

          $Params = @{
            App           = 'BOT'
            BuildName     = $env:BuildName
            ComponentName = $env:Component
            BasePath      = $env:Base
            OrgName       = $env:OrgName
            Location      = $env:location
            Environment   = $env:Environment
          }
          & ./Samples/PublicSamples/EchoBot/ADF/release-az/Update-AzBuildMetaData.ps1 @Params
        azPSVersion: latest
