name: .NET BOT D1 BUILD avtest5

on:
  workflow_dispatch:
    
  push:
    branches: [ main ]
    paths:
      - EchoBot/**
      - .github/workflows/app-build-*.yml
  pull_request:
    branches: [ main ]
    paths:
      - EchoBot/**
      - .github/workflows/app-build-*.yml

env:
  # /home/runner/work/publish
  Base:        publish
  Component:   EchoBot
  BuildName:   0.1.${{ github.run_number }}
  Environment: D1
  OrgName:     avtest5
  Location:    centralus

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    # Add wait on concurrent workflows executing via https://github.com/marketplace/actions/action-turnstyle
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Run pwsh
      shell: pwsh
      run: | 
        echo "${{ env.Base }}/${{ env.Component }}/${{ env.BuildName }}/"
    - uses: nuget/setup-nuget@v1
    - run: nuget restore EchoBot\EchoBot.sln
    
    - name: Create Build Directory
      run: mkdir ${{ env.Base }}/${{ env.Component }}/${{ env.BuildName }}/
    
    - name: Build Solution
      run: |
        msbuild.exe EchoBot\EchoBot.sln /nologo /p:platform="x64" /p:OutDir=../${{ env.Base }}/${{ env.Component }}/${{ env.BuildName }}/
        
    - name: Run pwsh
      shell: pwsh
      run: | 
        dir ${{ env.Base }}/${{ env.Component }}/${{ env.BuildName }}/
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_avtest5_BOT }}
        enable-AzPSSession: true

    - name: G1_RG_UploadArtifacts_to_Blob
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          Get-ChildItem -Path $env:GITHUB_WORKSPACE # -Recurse

          $Params = @{
            App           = 'BOT'
            BuildName     = $env:BuildName
            ComponentName = $env:Component
            BasePath      = "$env:GITHUB_WORKSPACE/$env:Component/$env:Base"
            OrgName       = $env:OrgName
            Location      = $env:location
          }
          & ./ADF/release-az/Sync-AzBuildComponent.ps1 @Params
        azPSVersion: latest

    - name: G1_RG_UpdateBuildMeta_to_Blob
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          echo $home
          ls $home

          $Params = @{
            App           = 'BOT'
            BuildName     = $env:BuildName
            ComponentName = $env:Component
            BasePath      = "$env:GITHUB_WORKSPACE/$env:Component/$env:Base"
            OrgName       = $env:OrgName
            Location      = $env:location
            Environment   = $env:Environment
          }
          & ./ADF/release-az/Update-AzBuildMetaData.ps1 @Params
        azPSVersion: latest

