name: .NET BOT D1 INFRA AHCK

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
  push:
    branches:
      - 'v2'
    paths:
      - './Samples/PublicSamples/EchoBot/ADF/**'
      - .github/workflows/echobot-infra-AHCK.yml

  pull_request:
    branches:
      - 'v2'
    paths:
      - './Samples/PublicSamples/EchoBot/ADF/**'
      - .github/workflows/echobot-infra-AHCK.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  OrgName: AHCK
  Location: eastus2

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  EnvironmentDeploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Add wait on concurrent workflows executing via https://github.com/marketplace/actions/action-turnstyle
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_AHCK_BOT}}
          enable-AzPSSession: true

      - name: Deploy_All_Subscription
        uses: Azure/powershell@v1
        with:
          azPSVersion: latest
          inlineScript: |
            $Params = @{
              OrgName         = $env:OrgName
              Location        = $env:location
              FullUpload      = $true
            }
            ./Samples/PublicSamples/EchoBot/ADF/main.ps1 @Params
            if ($e){throw $e}
        env:
          VMSS_CREDENTIALS: ${{ secrets.VMSS_CREDENTIALS_AHCK_BOT }}



