name: Recording Bot Release Docker Image

on:
  push:
    branches:
      - main
      - master
    paths:
      - Samples/PublicSamples/RecordingBot/**
      - .github/workflows/publicrecordingbot_release-docker-image.yml

jobs:
  build-push-cr:
    runs-on: windows-2022

    permissions:
      packages: write

    defaults:
      run:
        working-directory: Samples/PublicSamples/RecordingBot

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Tag docker image
        shell: bash
        run: |
          docker build -f ./build/Dockerfile . -t ${{ vars.CR_NAMESPACE_REPOSITORY }}:latest

      - name: Push docker image to CR
        shell: bash
        run: |
          docker push ${{ vars.CR_NAMESPACE_REPOSITORY }}:latest